INCLUDE(FindPkgConfig)
PKG_CHECK_MODULES(PC_GAUSSIAN_CODEBOOK gaussian_codebook)

FIND_PATH(
    GAUSSIAN_CODEBOOK_INCLUDE_DIRS
    NAMES gaussian_codebook/api.h
    HINTS $ENV{GAUSSIAN_CODEBOOK_DIR}/include
        ${PC_GAUSSIAN_CODEBOOK_INCLUDEDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/include
          /usr/local/include
          /usr/include
)

FIND_LIBRARY(
    GAUSSIAN_CODEBOOK_LIBRARIES
    NAMES gnuradio-gaussian_codebook
    HINTS $ENV{GAUSSIAN_CODEBOOK_DIR}/lib
        ${PC_GAUSSIAN_CODEBOOK_LIBDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/lib
          ${CMAKE_INSTALL_PREFIX}/lib64
          /usr/local/lib
          /usr/local/lib64
          /usr/lib
          /usr/lib64
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(GAUSSIAN_CODEBOOK DEFAULT_MSG GAUSSIAN_CODEBOOK_LIBRARIES GAUSSIAN_CODEBOOK_INCLUDE_DIRS)
MARK_AS_ADVANCED(GAUSSIAN_CODEBOOK_LIBRARIES GAUSSIAN_CODEBOOK_INCLUDE_DIRS)

